name: ReMonitor
options:
  bundleIdPrefix: io.github.knothole.remonitor
packages:
  ReSwift:
    url: https://github.com/ReSwift/ReSwift.git
    from: 5.0.0
  MirrorDiffKit:
    url: https://github.com/Kuniwak/MirrorDiffKit.git
    from: 5.0.1
  HighlightedTextEditor:
    url: https://github.com/kyle-n/HighlightedTextEditor.git
    from: 1.5.1
  SwiftPrettyPrint:
    url: https://github.com/YusukeHosonuma/SwiftPrettyPrint.git
    from: 1.0.0
targets:
  TestApp:
    type: application
    platform: macOS
    sources:
      - Sources/App
    dependencies:
      - target: ReMonitor
    preBuildScripts:
      - name: Swift Format
        script: |
          swift run -c release --package-path BuildTools swiftformat "$SRCROOT"
      - name: Swift Lint
        script: |
          swift run -c release --package-path BuildTools swiftlint --path "$SRCROOT"
  ReMonitor:
    type: framework
    platform: macOS
    sources:
      - Sources/Framework
    dependencies:
      - package: HighlightedTextEditor
      - package: MirrorDiffKit
      - package: ReSwift
      - package: SwiftPrettyPrint
    preBuildScripts:
      - name: Swift Format
        script: |
          swift run -c release --package-path BuildTools swiftformat "$SRCROOT"
      - name: Swift Lint
        script: |
          swift run -c release --package-path BuildTools swiftlint --path "$SRCROOT"
fileGroups:
  - .swiftlint.yml
  - Package.swift
  - README.md
  - project.yml
